#!/usr/bin/env python3
"""Generate the Mars dimension's datapack JSON (src/main/resources/data/...).

These files are generated by script (rather than hand-written) so the sol timeline stays consistent with the
24,660-tick period, the biome feature lists keep one canonical order (26.3's FeatureSorter rejects conflicting
orders), and every number traces to a single place. Values are documented in docs/SCIENCE.md.

Run: python3 tools/datagen/gen_mars_data.py
"""

from __future__ import annotations

import json
import math
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
DATA = REPO / "src/main/resources/data"

SOL = 24660                     # ticks per sol (88,775.244 s at 3.6 s per tick)
NOON = SOL // 4                 # vanilla convention: tick 0 = 06:00, noon a quarter period later
SUNSET = SOL // 2
DATUM_Y = 192
MIN_Y = 0
HEIGHT = 448

# --- planet parameters (docs/SCIENCE.md) ------------------------------------------------------------------
GRAVITY = 0.3794                # 3.721 / 9.80665 (effective mean incl. rotation; NSSDCA 3.73 GM/R^2)
PRESSURE_PA = 560.0             # annual-mean pressure at the MOLA zero level (SCIENCE.md section 3)
SCALE_HEIGHT_M = 11000.0        # NSSDCA
# Density at the datum from the ideal-gas law, relative to Earth's sea-level 1.225 kg/m3:
# rho = p M / (R T) with M = 43.34 g/mol and T = 210 K gives 0.0139 kg/m3 (NSSDCA: 0.016 +- 0.006 at 636 Pa).
AIR_DENSITY = round(PRESSURE_PA * 0.04334 / (8.314462618 * 210.0) / 1.225, 5)
RADIATION_MSV_PER_DAY = 0.64    # Curiosity RAD, Gale crater surface (Hassler et al. 2014)
SOUND_DAMPING = 0.7             # gain x0.3 (-10.5 dB); reality is ~-20 dB (Maurice et al. 2022), a compromise

# Colours (tuned against Curiosity/Perseverance true-colour images; see SCIENCE.md "Sky")
SKY_DAY = "#b98a63"             # butterscotch zenith
FOG_DAY = "#cfa27a"             # brighter, dustier horizon
SUNSET_BLUE = (0x6f, 0x9f, 0xe0)


def write(path: Path, obj) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        json.dump(obj, f, indent=2)
        f.write("\n")


def argb(alpha: float, rgb) -> str:
    a = max(0, min(255, round(alpha * 255)))
    return "#%02x%02x%02x%02x" % (a, rgb[0], rgb[1], rgb[2])


def dimension_type() -> dict:
    return {
        "has_skylight": True,
        "has_ceiling": False,
        "has_ender_dragon_fight": False,
        "coordinate_scale": 1.0,
        "min_y": MIN_Y,
        "height": HEIGHT,
        "logical_height": HEIGHT,
        "infiniburn": "#minecraft:infiniburn_overworld",
        "ambient_light": 0.0,
        "monster_spawn_light_level": 0,
        "monster_spawn_block_light_limit": 0,
        "skybox": "overworld",
        "cardinal_light": "default",
        "default_clock": "redplanet:mars",
        "timelines": "#redplanet:in_mars",
        "attributes": {
            "minecraft:visual/sky_color": SKY_DAY,
            "minecraft:visual/fog_color": FOG_DAY,
            "minecraft:visual/ambient_light_color": "#0a0a0a",
            "minecraft:visual/moon_phase": "new_moon",
            "minecraft:visual/fog_start_distance": 0.0,
            "minecraft:gameplay/water_evaporates": True,
            "minecraft:gameplay/can_start_raid": False,
            "minecraft:gameplay/respawn_anchor_works": False,
            "minecraft:gameplay/bed_rule": {
                "can_sleep": "never",
                "can_set_spawn": "never",
                "error_message": {"translate": "block.redplanet.bed.unpressurized"},
            },
            "redplanet:gameplay/gravity": GRAVITY,
            "redplanet:gameplay/air_density": AIR_DENSITY,
            "redplanet:gameplay/pressure": PRESSURE_PA,
            "redplanet:gameplay/breathable": False,
            "redplanet:gameplay/combustion": False,
            "redplanet:gameplay/radiation": RADIATION_MSV_PER_DAY,
            "redplanet:gameplay/scale_height": SCALE_HEIGHT_M,
            "redplanet:gameplay/datum_y": float(DATUM_Y),
            "redplanet:gameplay/vertical_scale": 100.0,
            "redplanet:audio/sound_damping": SOUND_DAMPING,
        },
    }


def sol_timeline() -> dict:
    """The sol: vanilla's day structure stretched to 24,660 ticks, with Mars' longer twilight (high-altitude dust
    keeps scattering sunlight for up to ~2 h after sunset), darker nights (no large moon), and a blue glow around
    the setting/rising Sun (forward scattering by ~1.5 um dust)."""
    bezier = {"cubic_bezier": [0.362, 0.241, 0.638, 0.759]}
    day_start, day_end = 330, 12000           # full daylight between these
    night_start, night_end = 14400, 22300     # full night between these (twilight ~2,400 ticks)

    def daynight(day_value, night_value):
        return [
            {"ticks": day_start, "value": day_value},
            {"ticks": day_end, "value": day_value},
            {"ticks": night_start, "value": night_value},
            {"ticks": night_end, "value": night_value},
        ]

    # Sunrise/sunset glow: alpha envelope peaking just after the Sun crosses the horizon.
    glow = []
    for centre, sign in ((SUNSET, 1), (0, -1)):
        for k in range(-7, 10):
            t = centre + k * 200 * sign
            phase = (k * 200 - 250) / 800.0
            a = 0.85 * math.exp(-phase * phase)
            tt = t % SOL
            glow.append({"ticks": tt, "value": argb(a, SUNSET_BLUE)})
    glow.sort(key=lambda kf: kf["ticks"])
    # at most 2 keyframes per tick; dedupe by tick keeping the larger alpha
    dedup = {}
    for kf in glow:
        prev = dedup.get(kf["ticks"])
        if prev is None or int(kf["value"][1:3], 16) > int(prev["value"][1:3], 16):
            dedup[kf["ticks"]] = kf
    glow = [dedup[t] for t in sorted(dedup)]

    stars = [
        {"ticks": 600, "value": 0.0},
        {"ticks": 11700, "value": 0.0},
        {"ticks": 12900, "value": 0.25},
        {"ticks": 14000, "value": 0.85},
        {"ticks": 22600, "value": 0.85},
        {"ticks": 23700, "value": 0.25},
    ]

    return {
        "clock": "redplanet:mars",
        "period_ticks": SOL,
        "time_markers": {
            "minecraft:wake_up_from_sleep": 0,
            "minecraft:day": {"ticks": round(1000 * SOL / 24000), "show_in_commands": True},
            "minecraft:noon": {"ticks": NOON, "show_in_commands": True},
            "minecraft:night": {"ticks": round(13000 * SOL / 24000), "show_in_commands": True},
            "minecraft:midnight": {"ticks": round(18000 * SOL / 24000), "show_in_commands": True},
            "redplanet:sunset": {"ticks": SUNSET, "show_in_commands": True},
        },
        "tracks": {
            "minecraft:visual/sun_angle": {"ease": bezier, "keyframes": [{"ticks": NOON, "value": 360.0}, {"ticks": NOON, "value": 0.0}]},
            "minecraft:visual/star_angle": {"ease": bezier, "keyframes": [{"ticks": NOON, "value": 360.0}, {"ticks": NOON, "value": 0.0}]},
            "minecraft:visual/moon_angle": {"keyframes": [{"ticks": 0, "value": 180.0}]},
            "minecraft:gameplay/sky_light_level": {"modifier": "multiply", "keyframes": daynight(1.0, 0.2)},
            "minecraft:visual/sky_light_factor": {"modifier": "multiply", "keyframes": daynight(1.0, 0.16)},
            "minecraft:visual/sky_light_color": {"modifier": "multiply", "keyframes": daynight("#ffffff", "#68687e")},
            "minecraft:visual/sky_color": {"modifier": "multiply", "keyframes": daynight("#ffffff", "#000000")},
            "minecraft:visual/fog_color": {"modifier": "multiply", "keyframes": daynight("#ffffff", "#0d0d12")},
            "minecraft:visual/star_brightness": {"modifier": "maximum", "keyframes": stars},
            "minecraft:visual/sunrise_sunset_color": {"keyframes": glow},
        },
    }


# Canonical feature order for all Mars biomes, per decoration step (filled in as features are added).
FEATURE_STEPS = 11


def biome(name: str, temperature: float, attributes: dict | None = None, features: list | None = None) -> dict:
    steps = [[] for _ in range(FEATURE_STEPS)]
    for step, fid in features or []:
        steps[step].append(fid)
    while steps and not steps[-1]:
        steps.pop()
    b = {
        "has_precipitation": False,
        "temperature": temperature,
        "downfall": 0.0,
        "effects": {"water_color": "#3f76e4"},
        "carvers": [],
        "features": steps,
    }
    if attributes:
        b["attributes"] = attributes
    return b


BIOMES = {
    # role: (temperature for vanilla freezing logic, positional attribute overrides)
    "northern_plains": (-0.7, {}),
    "cratered_highlands": (-0.6, {}),
    "dusty_highlands": (-0.6, {"minecraft:visual/fog_color": "#d6aa80"}),
    "volcanic_plains": (-0.6, {}),
    "shield_volcano": (-0.8, {}),
    "canyon": (-0.5, {}),
    "impact_basin": (-0.5, {"minecraft:visual/fog_color": "#d2a47c"}),
    "dune_field": (-0.6, {}),
    "north_polar_cap": (-1.0, {"minecraft:visual/fog_color": "#d8c4b0"}),
    "south_polar_cap": (-1.0, {"minecraft:visual/fog_color": "#d8c8bc"}),
    "mid_latitude_glaciers": (-0.8, {}),
    "meridiani_planum": (-0.5, {}),
    "gale_mound": (-0.5, {}),
    "jezero_delta": (-0.6, {}),
}


def noise_settings() -> dict:
    return {
        "noise": {"min_y": MIN_Y, "height": HEIGHT},
        "default_block": "redplanet:mars_stone",
        "default_fluid": "minecraft:air",
        "noise_router": {
            "temperature": 0.0,
            "vegetation": 0.0,
            "continents": 0.0,
            "erosion": 0.0,
            "depth": 0.0,
            "ridges": 0.0,
            "chunk_surface_level": "redplanet:mars/surface_height",
            "final_density": {
                "type": "minecraft:add",
                "left": {
                    "type": "minecraft:clamp",
                    "min": -1.0,
                    "max": 1.0,
                    "input": {
                        "type": "minecraft:mul",
                        "left": {"type": "minecraft:sub", "left": "redplanet:mars/surface_height", "right": "minecraft:y"},
                        "right": 0.1,
                    },
                },
                "right": {"type": "minecraft:beardifier"},
            },
        },
        "material_rule": {"type": "redplanet:mars_surface"},
        "spawn_target": [],
        "sea_level": MIN_Y,
        "disable_mob_generation": True,
        "legacy_random_source": False,
    }


def main() -> None:
    write(DATA / "redplanet/dimension_type/mars.json", dimension_type())
    write(DATA / "redplanet/world_clock/mars.json", {})
    write(DATA / "redplanet/timeline/mars_day.json", sol_timeline())
    write(DATA / "redplanet/tags/timeline/in_mars.json", {"values": ["redplanet:mars_day"]})
    write(DATA / "redplanet/worldgen/density_function/mars/surface_height.json",
          {"type": "minecraft:cache", "input": {"type": "redplanet:mars_height"}})
    write(DATA / "redplanet/worldgen/noise_settings/mars.json", noise_settings())
    for name, (temp, attrs) in BIOMES.items():
        write(DATA / f"redplanet/worldgen/biome/{name}.json", biome(name, temp, attrs))
    write(DATA / "redplanet/tags/worldgen/biome/is_mars.json", {"values": [f"redplanet:{n}" for n in BIOMES]})
    write(DATA / "redplanet/dimension/mars.json", {
        "type": "redplanet:mars",
        "generator": {
            "type": "minecraft:noise",
            "settings": "redplanet:mars",
            "biome_source": {"type": "redplanet:mars", "biomes": {n: f"redplanet:{n}" for n in BIOMES}},
        },
    })

    # Damage type: hypoxia (+ the same tags as vanilla drowning)
    write(DATA / "redplanet/damage_type/hypoxia.json",
          {"message_id": "redplanet.hypoxia", "scaling": "never", "exhaustion": 0.0, "effects": "drowning"})
    for tag in ("bypasses_armor", "bypasses_wolf_armor", "is_drowning", "no_impact", "no_knockback", "wither_immune_to"):
        write(DATA / f"minecraft/tags/damage_type/{tag}.json", {"replace": False, "values": ["redplanet:hypoxia"]})

    # Combustion and breathing tags
    write(DATA / "redplanet/tags/block/requires_oxygen.json", {"values": [
        "#minecraft:fire", "#minecraft:lanterns",
        "minecraft:torch", "minecraft:wall_torch", "minecraft:soul_torch", "minecraft:soul_wall_torch",
        {"id": "minecraft:copper_torch", "required": False}, {"id": "minecraft:copper_wall_torch", "required": False},
    ]})
    write(DATA / "redplanet/tags/block/extinguished_without_oxygen.json",
          {"values": ["#minecraft:campfires", "#minecraft:candles", "#minecraft:candle_cakes"]})
    write(DATA / "redplanet/tags/entity_type/does_not_breathe.json", {"values": [
        "#minecraft:undead", "minecraft:armor_stand", "minecraft:iron_golem", "minecraft:snow_golem",
        {"id": "minecraft:copper_golem", "required": False}, "minecraft:blaze", "minecraft:vex", "minecraft:allay",
        "minecraft:shulker", "minecraft:ender_dragon", "minecraft:enderman", "minecraft:endermite",
    ]})
    print("Mars data written under", DATA)


if __name__ == "__main__":
    main()
