#!/usr/bin/env python3
"""Generate the Mars dimension's datapack JSON (src/main/resources/data/...).

These files are generated by script (rather than hand-written) so the sol timeline stays consistent with the
24,660-tick period, the biome feature lists keep one canonical order (26.3's FeatureSorter rejects conflicting
orders), and every number traces to a single place. Values are documented in docs/SCIENCE.md.

Run: python3 tools/datagen/gen_mars_data.py
"""

from __future__ import annotations

import json
import math
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
DATA = REPO / "src/main/resources/data"

SOL = 24660                     # ticks per sol (88,775.244 s at 3.6 s per tick)
NOON = SOL // 4                 # vanilla convention: tick 0 = 06:00, noon a quarter period later
SUNSET = SOL // 2
DATUM_Y = 192
MIN_Y = 0
HEIGHT = 448

# --- planet parameters (docs/SCIENCE.md) ------------------------------------------------------------------
GRAVITY = 0.3794                # 3.721 / 9.80665 (effective mean incl. rotation; NSSDCA 3.73 GM/R^2)
PRESSURE_PA = 560.0             # annual-mean pressure at the MOLA zero level (SCIENCE.md section 3)
SCALE_HEIGHT_M = 11000.0        # NSSDCA
# Density at the datum from the ideal-gas law, relative to Earth's sea-level 1.225 kg/m3:
# rho = p M / (R T) with M = 43.34 g/mol and T = 210 K gives 0.0139 kg/m3 (NSSDCA: 0.016 +- 0.006 at 636 Pa).
AIR_DENSITY = round(PRESSURE_PA * 0.04334 / (8.314462618 * 210.0) / 1.225, 5)
RADIATION_MSV_PER_DAY = 0.64    # Curiosity RAD, Gale crater surface (Hassler et al. 2014)
SOUND_DAMPING = 0.7             # gain x0.3 (-10.5 dB); reality is ~-20 dB (Maurice et al. 2022), a compromise

# Colours (tuned against Curiosity/Perseverance true-colour images; see SCIENCE.md "Sky")
SKY_DAY = "#b98a63"             # butterscotch zenith
FOG_DAY = "#cfa27a"             # brighter, dustier horizon
SUNSET_BLUE = (0x6f, 0x9f, 0xe0)


def write(path: Path, obj) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        json.dump(obj, f, indent=2)
        f.write("\n")


def argb(alpha: float, rgb) -> str:
    a = max(0, min(255, round(alpha * 255)))
    return "#%02x%02x%02x%02x" % (a, rgb[0], rgb[1], rgb[2])


def dimension_type() -> dict:
    return {
        "has_skylight": True,
        "has_ceiling": False,
        "has_ender_dragon_fight": False,
        "coordinate_scale": 1.0,
        "min_y": MIN_Y,
        "height": HEIGHT,
        "logical_height": HEIGHT,
        "infiniburn": "#minecraft:infiniburn_overworld",
        "ambient_light": 0.0,
        "monster_spawn_light_level": 0,
        "monster_spawn_block_light_limit": 0,
        "skybox": "overworld",
        "cardinal_light": "default",
        "default_clock": "redplanet:mars",
        "timelines": "#redplanet:in_mars",
        "attributes": {
            "minecraft:visual/sky_color": SKY_DAY,
            "minecraft:visual/fog_color": FOG_DAY,
            "minecraft:visual/ambient_light_color": "#0a0a0a",
            "minecraft:visual/moon_phase": "new_moon",
            "minecraft:visual/fog_start_distance": 0.0,
            "minecraft:gameplay/water_evaporates": True,
            "minecraft:gameplay/can_start_raid": False,
            "minecraft:gameplay/respawn_anchor_works": False,
            "minecraft:gameplay/bed_rule": {
                "can_sleep": "never",
                "can_set_spawn": "never",
                "error_message": {"translate": "block.redplanet.bed.unpressurized"},
            },
            "redplanet:gameplay/gravity": GRAVITY,
            "redplanet:gameplay/air_density": AIR_DENSITY,
            "redplanet:gameplay/pressure": PRESSURE_PA,
            "redplanet:gameplay/breathable": False,
            "redplanet:gameplay/combustion": False,
            "redplanet:gameplay/radiation": RADIATION_MSV_PER_DAY,
            "redplanet:gameplay/scale_height": SCALE_HEIGHT_M,
            "redplanet:gameplay/datum_y": float(DATUM_Y),
            "redplanet:gameplay/vertical_scale": 100.0,
            "redplanet:audio/sound_damping": SOUND_DAMPING,
        },
    }


def sol_timeline() -> dict:
    """The sol: vanilla's day structure stretched to 24,660 ticks, with Mars' longer twilight (high-altitude dust
    keeps scattering sunlight for up to ~2 h after sunset), darker nights (no large moon), and a blue glow around
    the setting/rising Sun (forward scattering by ~1.5 um dust)."""
    bezier = {"cubic_bezier": [0.362, 0.241, 0.638, 0.759]}
    day_start, day_end = 330, 12000           # full daylight between these
    night_start, night_end = 14400, 22300     # full night between these (twilight ~2,400 ticks)

    def daynight(day_value, night_value):
        return [
            {"ticks": day_start, "value": day_value},
            {"ticks": day_end, "value": day_value},
            {"ticks": night_start, "value": night_value},
            {"ticks": night_end, "value": night_value},
        ]

    # Sunrise/sunset glow: alpha envelope peaking just after the Sun crosses the horizon.
    glow = []
    for centre, sign in ((SUNSET, 1), (0, -1)):
        for k in range(-7, 10):
            t = centre + k * 200 * sign
            phase = (k * 200 - 250) / 800.0
            a = 0.85 * math.exp(-phase * phase)
            tt = t % SOL
            glow.append({"ticks": tt, "value": argb(a, SUNSET_BLUE)})
    glow.sort(key=lambda kf: kf["ticks"])
    # at most 2 keyframes per tick; dedupe by tick keeping the larger alpha
    dedup = {}
    for kf in glow:
        prev = dedup.get(kf["ticks"])
        if prev is None or int(kf["value"][1:3], 16) > int(prev["value"][1:3], 16):
            dedup[kf["ticks"]] = kf
    glow = [dedup[t] for t in sorted(dedup)]

    stars = [
        {"ticks": 600, "value": 0.0},
        {"ticks": 11700, "value": 0.0},
        {"ticks": 12900, "value": 0.25},
        {"ticks": 14000, "value": 0.85},
        {"ticks": 22600, "value": 0.85},
        {"ticks": 23700, "value": 0.25},
    ]

    return {
        "clock": "redplanet:mars",
        "period_ticks": SOL,
        "time_markers": {
            "minecraft:wake_up_from_sleep": 0,
            "minecraft:day": {"ticks": round(1000 * SOL / 24000), "show_in_commands": True},
            "minecraft:noon": {"ticks": NOON, "show_in_commands": True},
            "minecraft:night": {"ticks": round(13000 * SOL / 24000), "show_in_commands": True},
            "minecraft:midnight": {"ticks": round(18000 * SOL / 24000), "show_in_commands": True},
            "redplanet:sunset": {"ticks": SUNSET, "show_in_commands": True},
        },
        "tracks": {
            "minecraft:visual/sun_angle": {"ease": bezier, "keyframes": [{"ticks": NOON, "value": 360.0}, {"ticks": NOON, "value": 0.0}]},
            "minecraft:visual/star_angle": {"ease": bezier, "keyframes": [{"ticks": NOON, "value": 360.0}, {"ticks": NOON, "value": 0.0}]},
            "minecraft:visual/moon_angle": {"keyframes": [{"ticks": 0, "value": 180.0}]},
            "minecraft:gameplay/sky_light_level": {"modifier": "multiply", "keyframes": daynight(1.0, 0.2)},
            "minecraft:visual/sky_light_factor": {"modifier": "multiply", "keyframes": daynight(1.0, 0.16)},
            "minecraft:visual/sky_light_color": {"modifier": "multiply", "keyframes": daynight("#ffffff", "#68687e")},
            "minecraft:visual/sky_color": {"modifier": "multiply", "keyframes": daynight("#ffffff", "#000000")},
            "minecraft:visual/fog_color": {"modifier": "multiply", "keyframes": daynight("#ffffff", "#0d0d12")},
            "minecraft:visual/star_brightness": {"modifier": "maximum", "keyframes": stars},
            "minecraft:visual/sunrise_sunset_color": {"keyframes": glow},
        },
    }


# Canonical feature order for all Mars biomes, per decoration step (filled in as features are added).
FEATURE_STEPS = 11


# Carvers: drained lava tubes under the volcanic provinces (redplanet:lava_tube, which follows the local surface) and
# ordinary caves in the deep crust everywhere but the ice caps.
CARVERS = {
    "lava_tube": {"type": "redplanet:lava_tube", "probability": 0.02,
                  "depth": {"type": "minecraft:uniform", "min_inclusive": 10, "max_inclusive": 28},
                  "radius": {"type": "minecraft:uniform", "min_inclusive": 4.0, "max_exclusive": 8.0},
                  "length": {"type": "minecraft:uniform", "min_inclusive": 80, "max_inclusive": 200},
                  "skylight_chance": 0.012},
    "mars_cave": {"type": "minecraft:cave", "probability": 0.08,
                  "y": {"type": "minecraft:uniform", "min_inclusive": {"above_bottom": 8}, "max_inclusive": {"absolute": 120}},
                  "count": {"type": "minecraft:very_biased_to_bottom", "min_inclusive": 0, "max_inclusive": 8},
                  "thickness": {"type": "minecraft:trapezoid", "min": 0.0, "max": 3.5, "plateau": 1.0},
                  "weird_thickness_bias": True,
                  "room_vertical_radius_multiplier": {"type": "minecraft:uniform", "min_inclusive": 0.2, "max_exclusive": 1.0},
                  "horizontal_radius_multiplier": {"type": "minecraft:uniform", "min_inclusive": 1.0, "max_exclusive": 1.7},
                  "vertical_radius_multiplier": {"type": "minecraft:uniform", "min_inclusive": 0.8, "max_exclusive": 1.4},
                  "floor_level": {"type": "minecraft:uniform", "min_inclusive": -1.0, "max_exclusive": -0.4}},
}
VOLCANIC = {"volcanic_plains", "shield_volcano"}
ICE_CAPS = {"north_polar_cap", "south_polar_cap"}


def biome_carvers(name: str) -> list:
    if name in ICE_CAPS:
        return []
    return (["redplanet:lava_tube"] if name in VOLCANIC else []) + ["redplanet:mars_cave"]


def biome(name: str, temperature: float, attributes: dict | None = None, features: list | None = None) -> dict:
    steps = [[] for _ in range(FEATURE_STEPS)]
    for step, fid in features or []:
        steps[step].append(fid)
    while steps and not steps[-1]:
        steps.pop()
    b = {
        "has_precipitation": False,
        "temperature": temperature,
        "downfall": 0.0,
        "effects": {"water_color": "#3f76e4"},
        "carvers": biome_carvers(name),
        "features": steps,
    }
    attrs = dict(MARS_AMBIENCE)
    attrs.update(attributes or {})
    b["attributes"] = attrs
    return b


# Every Mars biome: the thin wind (low-passed when generated, tools/sounds), no music by default, and a faint drift
# of airborne dust. Dust storms add much more dust on the client (MarsSkyClient).
MARS_DUST_PARTICLE = {"type": "minecraft:dust", "color": [0.74, 0.50, 0.33], "scale": 0.55}
MARS_AMBIENCE = {
    "minecraft:audio/ambient_sounds": {"loop": "redplanet:mars.wind"},
    "minecraft:visual/ambient_particles": {
        "modifier": "append",
        "argument": [{"particle": MARS_DUST_PARTICLE, "probability": 0.0012}],
    },
}


BIOMES = {
    # role: (temperature for vanilla freezing logic, positional attribute overrides)
    "northern_plains": (-0.7, {}),
    "cratered_highlands": (-0.6, {}),
    "dusty_highlands": (-0.6, {"minecraft:visual/fog_color": "#d6aa80"}),
    "volcanic_plains": (-0.6, {}),
    "shield_volcano": (-0.8, {}),
    "canyon": (-0.5, {}),
    "impact_basin": (-0.5, {"minecraft:visual/fog_color": "#d2a47c"}),
    "dune_field": (-0.6, {}),
    "north_polar_cap": (-1.0, {"minecraft:visual/fog_color": "#d8c4b0"}),
    "south_polar_cap": (-1.0, {"minecraft:visual/fog_color": "#d8c8bc"}),
    "mid_latitude_glaciers": (-0.8, {}),
    "meridiani_planum": (-0.5, {}),
    "gale_mound": (-0.5, {}),
    "jezero_delta": (-0.6, {}),
}



# --- features ------------------------------------------------------------------------------------------------------
# Decoration steps (GenerationStep.Decoration ordinals).
LOCAL_MODIFICATIONS = 2
UNDERGROUND_ORES = 6
VEGETAL_DECORATION = 9

ORE_HOSTS = "#redplanet:mars_ore_replaceables"


def ore(state: str, size: int, hosts: str = ORE_HOSTS, air_discard: float = 0.0) -> dict:
    return {"type": "minecraft:ore", "discard_chance_on_air_exposure": air_discard, "size": size,
            "targets": [{"state": state, "target": {"predicate_type": "minecraft:tag_match", "tag": hosts[1:]}}]}


def ore_placement(feature: str, count: int, low: int, high: int) -> dict:
    return {"feature": feature, "placement": [
        {"type": "minecraft:count", "count": count},
        {"type": "minecraft:in_square"},
        {"type": "minecraft:height_range", "height": {"type": "minecraft:uniform",
                                                      "min_inclusive": {"absolute": low}, "max_inclusive": {"absolute": high}}},
        {"type": "minecraft:biome"}]}


def surface_placement(feature: str, *, count: int | None = None, rarity: int | None = None) -> dict:
    placement = []
    if rarity:
        placement.append({"type": "minecraft:rarity_filter", "chance": rarity})
    if count:
        placement.append({"type": "minecraft:count", "count": count})
    placement += [{"type": "minecraft:in_square"},
                  {"type": "minecraft:heightmap", "heightmap": "WORLD_SURFACE_WG"},
                  {"type": "minecraft:biome"}]
    return {"feature": feature, "placement": placement}


ROCKS = {"type": "minecraft:weighted", "entries": [
    {"data": "redplanet:mars_stone", "weight": 5}, {"data": "redplanet:mars_cobblestone", "weight": 3},
    {"data": "redplanet:mars_basalt", "weight": 2}]}
BASALT_ROCKS = {"type": "minecraft:weighted", "entries": [
    {"data": "redplanet:mars_basalt", "weight": 6}, {"data": "redplanet:olivine_basalt", "weight": 1},
    {"data": "redplanet:mars_cobblestone", "weight": 1}]}

# Configured features: id -> JSON. Craters: depth/diameter 0.2, see SmallCraterFeature.
FEATURES = {
    "small_crater": {"type": "redplanet:small_crater", "radius": {"type": "minecraft:uniform", "min_inclusive": 3, "max_inclusive": 9},
                     "fresh_chance": 0.15, "meteorite_chance": 0.25},
    "boulder": {"type": "redplanet:boulder", "block": ROCKS,
                "size": {"type": "minecraft:weighted_list", "distribution": [
                    {"data": 0, "weight": 6}, {"data": 1, "weight": 3}, {"data": 2, "weight": 1}]}},
    "basalt_boulder": {"type": "redplanet:boulder", "block": BASALT_ROCKS,
                       "size": {"type": "minecraft:weighted_list", "distribution": [
                           {"data": 0, "weight": 5}, {"data": 1, "weight": 3}, {"data": 2, "weight": 2}]}},
    "large_boulder": {"type": "redplanet:boulder", "block": ROCKS, "size": {"type": "minecraft:uniform", "min_inclusive": 2, "max_inclusive": 3}},
    "meteorite_fragment": {"type": "minecraft:simple_block",
                           "to_place": {"type": "minecraft:simple", "state": "redplanet:iron_nickel_meteorite"}},
    # Ores (UNDERGROUND_ORES): geology in docs/SCIENCE.md section 14.
    "ore_hematite": ore("redplanet:hematite_ore", 8),
    "ore_olivine": ore("redplanet:olivine_basalt", 14),
    "ore_jarosite": ore("redplanet:jarosite_ore", 8),
    "ore_gypsum": ore("redplanet:gypsum_vein", 6),
    "ore_sulfur": ore("redplanet:sulfur_deposit", 5),
    "ore_mars_chromite": ore("redplanet:mars_chromite_ore", 6),
    # Earth: chromite in the deep overworld (ultramafic rock), added to overworld biomes by RPWorldgen.
    "ore_chromite": {"type": "minecraft:ore", "discard_chance_on_air_exposure": 0.0, "size": 7, "targets": [
        {"state": "redplanet:chromite_ore", "target": {"predicate_type": "minecraft:tag_match", "tag": "minecraft:stone_ore_replaceables"}},
        {"state": "redplanet:deepslate_chromite_ore",
         "target": {"predicate_type": "minecraft:tag_match", "tag": "minecraft:deepslate_ore_replaceables"}}]},
}

PLACED = {
    "small_crater_common": surface_placement("redplanet:small_crater", rarity=2),
    "small_crater": surface_placement("redplanet:small_crater", rarity=4),
    "small_crater_rare": surface_placement("redplanet:small_crater", rarity=12),
    "boulders_scattered": surface_placement("redplanet:boulder", count=2),
    "boulders_dense": surface_placement("redplanet:boulder", count=6),
    "basalt_boulders": surface_placement("redplanet:basalt_boulder", count=4),
    "large_boulder": surface_placement("redplanet:large_boulder", rarity=3),
    "meteorite_fragment": surface_placement("redplanet:meteorite_fragment", rarity=48),
    "meteorite_fragment_common": surface_placement("redplanet:meteorite_fragment", rarity=12),
    "ore_hematite": ore_placement("redplanet:ore_hematite", 6, 20, 330),
    "ore_hematite_rich": ore_placement("redplanet:ore_hematite", 20, 60, 330),
    "ore_olivine": ore_placement("redplanet:ore_olivine", 5, 20, 400),
    "ore_jarosite": ore_placement("redplanet:ore_jarosite", 6, 60, 330),
    "ore_gypsum": ore_placement("redplanet:ore_gypsum", 10, 60, 330),
    "ore_sulfur": ore_placement("redplanet:ore_sulfur", 3, 100, 300),
    "ore_mars_chromite": ore_placement("redplanet:ore_mars_chromite", 3, 10, 260),
    "ore_chromite": {"feature": "redplanet:ore_chromite", "placement": [
        {"type": "minecraft:count", "count": 5}, {"type": "minecraft:in_square"},
        {"type": "minecraft:height_range", "height": {"type": "minecraft:trapezoid",
                                                      "min_inclusive": {"absolute": -64}, "max_inclusive": {"absolute": 40}}},
        {"type": "minecraft:biome"}]},
}

# One canonical order per step (26.3's FeatureSorter rejects conflicting orders between biomes).
CANONICAL = [
    (LOCAL_MODIFICATIONS, ["small_crater_common", "small_crater", "small_crater_rare"]),
    (UNDERGROUND_ORES, ["ore_hematite", "ore_hematite_rich", "ore_olivine", "ore_jarosite", "ore_gypsum", "ore_sulfur", "ore_mars_chromite"]),
    (VEGETAL_DECORATION, ["boulders_scattered", "boulders_dense", "basalt_boulders", "large_boulder", "meteorite_fragment",
                          "meteorite_fragment_common"]),
]

BIOME_FEATURES = {
    "northern_plains": ["small_crater", "ore_hematite", "ore_mars_chromite", "boulders_dense", "large_boulder", "meteorite_fragment"],
    "cratered_highlands": ["small_crater_common", "ore_hematite", "ore_olivine", "ore_mars_chromite", "boulders_scattered", "large_boulder",
                           "meteorite_fragment"],
    "dusty_highlands": ["small_crater", "ore_hematite", "boulders_scattered", "meteorite_fragment"],
    "volcanic_plains": ["small_crater_rare", "ore_hematite", "ore_olivine", "ore_mars_chromite", "basalt_boulders", "meteorite_fragment"],
    "shield_volcano": ["small_crater_rare", "ore_olivine", "ore_mars_chromite", "basalt_boulders"],
    "canyon": ["small_crater_rare", "ore_hematite", "ore_jarosite", "ore_gypsum", "ore_sulfur", "boulders_dense", "large_boulder"],
    "impact_basin": ["small_crater", "ore_hematite", "ore_olivine", "boulders_scattered", "meteorite_fragment"],
    "dune_field": ["small_crater_rare", "ore_hematite"],
    "north_polar_cap": [],
    "south_polar_cap": [],
    "mid_latitude_glaciers": ["small_crater_rare", "ore_hematite", "boulders_scattered"],
    "meridiani_planum": ["small_crater", "ore_hematite_rich", "ore_jarosite", "meteorite_fragment_common"],
    "gale_mound": ["small_crater_rare", "ore_hematite", "ore_jarosite", "ore_gypsum", "ore_sulfur", "boulders_scattered"],
    "jezero_delta": ["small_crater", "ore_hematite", "ore_olivine", "boulders_scattered", "meteorite_fragment"],
}


def biome_feature_list(name: str) -> list:
    wanted = set(BIOME_FEATURES[name])
    out = []
    for step, ordered in CANONICAL:
        for fid in ordered:
            if fid in wanted:
                out.append((step, f"redplanet:{fid}"))
    return out

def noise_settings() -> dict:
    return {
        "noise": {"min_y": MIN_Y, "height": HEIGHT},
        "default_block": "redplanet:mars_stone",
        "default_fluid": "minecraft:air",
        "noise_router": {
            "temperature": 0.0,
            "vegetation": 0.0,
            "continents": 0.0,
            "erosion": 0.0,
            "depth": 0.0,
            "ridges": 0.0,
            "chunk_surface_level": "redplanet:mars/surface_height",
            "final_density": {
                "type": "minecraft:add",
                "left": {
                    "type": "minecraft:clamp",
                    "min": -1.0,
                    "max": 1.0,
                    "input": {
                        "type": "minecraft:mul",
                        "left": {"type": "minecraft:sub", "left": "redplanet:mars/surface_height", "right": "minecraft:y"},
                        "right": 0.1,
                    },
                },
                "right": {"type": "minecraft:beardifier"},
            },
        },
        "material_rule": {"type": "redplanet:mars_surface"},
        "spawn_target": [],
        "sea_level": MIN_Y,
        "disable_mob_generation": True,
        "legacy_random_source": False,
    }


def main() -> None:
    write(DATA / "redplanet/dimension_type/mars.json", dimension_type())
    write(DATA / "redplanet/world_clock/mars.json", {})
    write(DATA / "redplanet/timeline/mars_day.json", sol_timeline())
    write(DATA / "redplanet/tags/timeline/in_mars.json", {"values": ["redplanet:mars_day"]})
    write(DATA / "redplanet/worldgen/density_function/mars/surface_height.json",
          {"type": "minecraft:cache", "input": {"type": "redplanet:mars_height"}})
    write(DATA / "redplanet/worldgen/noise_settings/mars.json", noise_settings())
    for cid, carver in CARVERS.items():
        write(DATA / f"redplanet/worldgen/carver/{cid}.json", carver)
    for fid, feature in FEATURES.items():
        write(DATA / f"redplanet/worldgen/feature/{fid}.json", feature)
    for pid, placed in PLACED.items():
        write(DATA / f"redplanet/worldgen/placed_feature/{pid}.json", placed)
    write(DATA / "redplanet/tags/block/mars_ore_replaceables.json", {"values": [
        "redplanet:mars_stone", "redplanet:mars_basalt", "redplanet:mudstone", "redplanet:layered_sediment",
        "redplanet:delta_sediment", "redplanet:carbonate_rock"]})
    for name, (temp, attrs) in BIOMES.items():
        write(DATA / f"redplanet/worldgen/biome/{name}.json", biome(name, temp, attrs, biome_feature_list(name)))
    write(DATA / "redplanet/tags/worldgen/biome/is_mars.json", {"values": [f"redplanet:{n}" for n in BIOMES]})
    write(DATA / "redplanet/dimension/mars.json", {
        "type": "redplanet:mars",
        "generator": {
            "type": "minecraft:noise",
            "settings": "redplanet:mars",
            "biome_source": {"type": "redplanet:mars", "biomes": {n: f"redplanet:{n}" for n in BIOMES}},
        },
    })

    # Damage type: hypoxia (+ the same tags as vanilla drowning)
    write(DATA / "redplanet/damage_type/hypoxia.json",
          {"message_id": "redplanet.hypoxia", "scaling": "never", "exhaustion": 0.0, "effects": "drowning"})
    for tag in ("bypasses_armor", "bypasses_wolf_armor", "is_drowning", "no_impact", "no_knockback", "wither_immune_to"):
        write(DATA / f"minecraft/tags/damage_type/{tag}.json", {"replace": False, "values": ["redplanet:hypoxia"]})

    # Combustion and breathing tags
    write(DATA / "redplanet/tags/block/requires_oxygen.json", {"values": [
        "#minecraft:fire", "#minecraft:lanterns",
        "minecraft:torch", "minecraft:wall_torch", "minecraft:soul_torch", "minecraft:soul_wall_torch",
        {"id": "minecraft:copper_torch", "required": False}, {"id": "minecraft:copper_wall_torch", "required": False},
    ]})
    write(DATA / "redplanet/tags/block/extinguished_without_oxygen.json",
          {"values": ["#minecraft:campfires", "#minecraft:candles", "#minecraft:candle_cakes"]})
    write(DATA / "redplanet/tags/entity_type/does_not_breathe.json", {"values": [
        "#minecraft:undead", "minecraft:armor_stand", "minecraft:iron_golem", "minecraft:snow_golem",
        {"id": "minecraft:copper_golem", "required": False}, "minecraft:blaze", "minecraft:vex", "minecraft:allay",
        "minecraft:shulker", "minecraft:ender_dragon", "minecraft:enderman", "minecraft:endermite",
    ]})
    print("Mars data written under", DATA)


if __name__ == "__main__":
    main()
